version: '3.5'

services:
  boilerplate-laravel-10-clean-architecture:
    container_name: boilerplate-laravel-10-clean-architecture
    # image: your image
    restart: always
    env_file:
      - stack.env
    ports:
      - 4010:80
