version: '3.5'
services:
  boilerplate-laravel-10-clean-architecture:
    container_name: boilerplate-laravel-10-clean-architecture
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app/boilerplate-laravel-10-clean-architecture
      - volume-boilerplate-laravel-10-clean-architecture-vendor:/app/boilerplate-laravel-10-clean-architecture/vendor
      - volume-boilerplate-laravel-10-clean-architecture-node_modules:/app/boilerplate-laravel-10-clean-architecture/node_modules
    networks:
      - boilerplate-laravel-10-clean-architecture-network
      - mysql-network
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

volumes:
 volume-boilerplate-laravel-10-clean-architecture-vendor:
  name: volume-boilerplate-laravel-10-clean-architecture-vendor
 volume-boilerplate-laravel-10-clean-architecture-node_modules:
  name: volume-boilerplate-laravel-10-clean-architecture-node_modules

networks:
   boilerplate-laravel-10-clean-architecture-network:
    name: boilerplate-laravel-10-clean-architecture-network
    driver: bridge
   mysql-network:
    name: mysql-network
    external: true

