name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  docker_portainer:
    name: CI
    uses: GabrielSoares-Dev/workflows/.github/workflows/laravel-docker-portainer-CI.yml@master
    with:
      php_version: '8.1'