name: DEPLOY
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - uses: docker/build-push-action@v4
        with:
          push: false
          context: .
          file: Dockerfile.prod
          tags: gabrielsoaresdev/boilerplate-laravel-10:latest
      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: gabrielsoaresdev/boilerplate-laravel-10:latest
          tag: "slim"

      - run: docker image push "gabrielsoaresdev/boilerplate-laravel-10" --all-tags
